#!/system/bin/sh

if busybox [ -f /system/etc/hostname ]; then
	export HOSTNAME=$(busybox cat /system/etc/hostname)
fi

if busybox [ -z "$HOSTNAME" ]; then
	export HOSTNAME="localhost"
fi

busybox mount -o remount,rw /system

if busybox [ ! -f /system/etc/hosts ]; then
	busybox echo "127.0.0.1 localhost localdomain" > /system/etc/hosts

elif busybox [ -z "`busybox cat /system/etc/hosts | busybox grep -e '127\.0\.0\.1[^\.]\+$'`" ]; then
	busybox echo "127.0.0.1 localhost localdomain" >> /system/etc/hosts

elif busybox [ -z "`busybox cat /system/etc/hosts | busybox grep -e '127\.0\.0\.1[^\.]\+$' | busybox grep 'localhost'`" ]; then
	FILE_LINE="`busybox cat /system/etc/hosts | busybox grep '127.0.0.1' | busybox head -n1`"

	busybox sed "s/$FILE_LINE/127.0.0.1 localhost/g" /system/etc/hosts > /system/etc/hosts.tmp
	busybox mv -f /system/etc/hosts.tmp /system/etc/hosts
fi

if busybox [ "$HOSTNAME" != "localhost" ]; then
	if busybox [ -z "`busybox cat /system/etc/hosts | busybox grep -e '127\.0\.0\.1[^\.]\+$' | busybox grep -v 'localhost'`" ]; then
		busybox echo "127.0.0.1 $HOSTNAME" >> /system/etc/hosts

	elif busybox [ -z "`busybox cat /system/etc/hosts | busybox grep -e '127\.0\.0\.1[^\.]\+$' | grep "$HOSTNAME"`" ]; then
		FILE_LINE="`busybox cat /system/etc/hosts | busybox grep -e '127\.0\.0\.1[^\.]\+$' | busybox grep -v 'localhost' | busybox head -n1`"

		busybox sed "s/$FILE_LINE/127.0.0.1 $HOSTNAME/g" /system/etc/hosts > /system/etc/hosts.tmp
		busybox mv -f /system/etc/hosts.tmp /system/etc/hosts
	fi
fi

busybox mount -o remount,ro /system

busybox echo $HOSTNAME > /proc/sys/kernel/hostname
setprop net.hostname $HOSTNAME
