#!/system/bin/sh

M2SD_VERSION="2.2.6"
M2SD_PROPERTIES="rmount:disable:boolean noatime:disable:boolean dlcache:disable:boolean memcache:disable:boolean extfs:auto:fstype sysapps:disable:boolean apps:enable:boolean data:disable:boolean cmdalvik:disable:boolean dalvik:disable:boolean cache:auto:option swap:disable:boolean readahead:512:integer journal:disable:boolean fschk:enable:boolean"
M2SD_CONFIGS=/data/.m2sd
M2SD_BB=/system/xbin/busybox.m2sd
TOOLBOX=/system/bin/toolbox

# =========================================================================================
# SET LOG FUNCTION
# =========================================================================================
doLog() {
	$M2SD_BB [ -z "$2" ] && LOG_LEVEL="$0" || LOG_LEVEL="$1"
	$M2SD_BB [ -z "$2" ] && LOG_MSG="$1" || LOG_MSG="$2"

	$TOOLBOX log -p $LOG_LEVEL -t mounts2sd "$LOG_MSG"

	if $M2SD_BB [ -z "$TMP_LABE" ]; then
		export TMP_LABE="TRUE"

		$M2SD_BB echo "" > $M2SD_CONFIGS/m2sd.log
	fi

	$M2SD_BB echo "$LOG_LEVEL/$LOG_MSG" >> $M2SD_CONFIGS/m2sd.log
}

# =========================================================================================
# SCRIPT CALL PART
# =========================================================================================

# This is used as a hack to break out of at any time
for ohack in true; do

	$M2SD_BB test 2> /dev/null

	# This is a hacked way of checking whether or not the m2sd busybox exists or not.
	# Some toolbox versions are so limited that they don't even support basic echo command, and most are missing things like [ to make proper conditional checks using if and else.
	case "$?" in
		"1") ;;

		*)
			# Maybe we have a basic busybox available
			busybox test 2> /dev/null

			case "$?" in
				"1") 
					busybox echo "Missing Mounts2SD Busybox!"
				;;
			esac

			$TOOLBOX log -p e -t mounts2sd "Missing Mounts2SD Busybox!"

			# Break the loop
			break
		;;
	esac

	if $M2SD_BB [ ! -d $M2SD_CONFIGS ]; then
		$M2SD_BB mkdir -p $M2SD_CONFIGS
		$M2SD_BB chown 1000.1000 $M2SD_CONFIGS
	fi

	CALL_BASENAME="`$M2SD_BB basename $0`"

	# =========================================================================================
	# CONFIGURATION PART
	# =========================================================================================
	if $M2SD_BB [ "$CALL_BASENAME" = "m2sd" ] || ( $M2SD_BB [ ! -z "$1" ] && $M2SD_BB [ "`$M2SD_BB basename $1`" = "m2sd" ] ); then
		if $M2SD_BB [ "`$M2SD_BB id | $M2SD_BB sed -ne "s/^uid=\([0-9]\+\)[^0-9].*$/\1/p"`" != "0" ]; then
			$M2SD_BB echo "You need to be root to access m2sd configurations. Type 'su' in console to gain superuser privileges!"
		
		else
			if [ "`props get mounts2sd.rmount.status`" = "loaded" ]; then
				M2SD_CONFIGS=/sd-ext/.m2sd
			fi

			$M2SD_BB [ "$CALL_BASENAME" = "m2sd" ] && INAME="$1" || INAME="$2"
			$M2SD_BB [ "$CALL_BASENAME" = "m2sd" ] && IVALUE="$2" || IVALUE="$3"

			case "$INAME" in
				""|"help"|"--help"|"-h") 
					$M2SD_BB echo ""
					$M2SD_BB echo " Usage: m2sd [index]		: Get value from index" 
					$M2SD_BB echo " Usage: m2sd [index] [value]	: Change current value"
					$M2SD_BB echo ""
					$M2SD_BB echo " - apps [disable/enable]	: Enable/disable apps2sd"
					$M2SD_BB echo " - sysapps [disable/enable]	: Enable/disable sysapps2sd (System app linking)"
					$M2SD_BB echo " - dalvik [disable/enable]	: Enable/disable dalvik2sd"
					$M2SD_BB echo " - cmdalvik [disable/enable]	: Enable/disable CyanogenMod dalvik fix (/cache to /data)"
					$M2SD_BB echo " - data [disable/enable]	: Enable/disable data2sd (/data/data)"
					$M2SD_BB echo " - cache [disable/enable/auto]	: Enable/disable cache2sd"
					$M2SD_BB echo " - memcache [disable/enable]	: Use tmpfs instead of a sd-ext or data partition for the cache."
					$M2SD_BB echo " - dlcache [disable/enable]	: Replace /cache/download/ instead of /cache/"
					$M2SD_BB echo " - swap [disable/enable]	: Enable/disable swap"
					$M2SD_BB echo " - journal [disable/enable]	: Enable/disable ext(3,4) journal on sd-ext"
					$M2SD_BB echo " - fschk [disable/enable]	: Enable/disable file system check during boot"
					$M2SD_BB echo " - noatime [disable/enable]	: Mount /data and /sd-ext with noatime"
					$M2SD_BB echo " - rmount [disable/enable]	: Reversed mount. sd-ext on /data and data on /sd-ext"
					$M2SD_BB echo " - readahead [0-9]		: Set sdcard readahead (In kb)"
					$M2SD_BB echo " - extfs [auto/<fs-type>]	: Force a specific fs type on /sd-ext mount"
					$M2SD_BB echo ""
					$M2SD_BB echo "Info:"
					$M2SD_BB echo "-----"
					$M2SD_BB echo " - log				: Get the log from last boot"
					$M2SD_BB echo " - status			: Get the status"
					$M2SD_BB echo " - version			: Get current version"
					$M2SD_BB echo ""
					$M2SD_BB echo "Actions:"
					$M2SD_BB echo "--------"
					$M2SD_BB echo " - fixperm			: Do a one time permissions check and fix them if needed"
					$M2SD_BB echo ""
				;;

				"log")
					if $M2SD_BB [ -f $M2SD_CONFIGS/m2sd.log ] && $M2SD_BB [ ! -z "`$M2SD_BB cat $M2SD_CONFIGS/m2sd.log`" ]; then
						$M2SD_BB cat $M2SD_CONFIGS/m2sd.log

					else
						$M2SD_BB echo " - Log file is empty!"
					fi
				;;

				"status") 
					$M2SD_BB echo ""
					$M2SD_BB echo "Status:"
					$M2SD_BB echo "-------"
					$M2SD_BB echo "Mounts2SD [`props get mounts2sd.status`]"
					$M2SD_BB echo " - Apps [`props get mounts2sd.sdext.status.apps`]"
					$M2SD_BB echo " - SysApps [`props get mounts2sd.sdext.status.sysapps`]"
					$M2SD_BB echo " - Data [`props get mounts2sd.sdext.status.data`]"
					$M2SD_BB echo " - Dalvik [`props get mounts2sd.sdext.status.dalvik`]"
					$M2SD_BB echo " - CmDalvik [`props get mounts2sd.cmdalvik.status`]"
					$M2SD_BB echo " - Cache [`props get mounts2sd.cache.status`]"
					$M2SD_BB echo " - SWAP [`props get mounts2sd.swap.status`]"
					$M2SD_BB echo " - RMount [`props get mounts2sd.rmount.status`]"
					$M2SD_BB echo ""
					$M2SD_BB echo "Device info:"
					$M2SD_BB echo "------------"
					$M2SD_BB echo "SD-EXT device [`props get mounts2sd.sdext.device`]"
					$M2SD_BB echo "Cache device [`props get mounts2sd.cache.device`]"
					$M2SD_BB echo " - Location [`props get mounts2sd.cache.location`]"
					$M2SD_BB echo "Swap device [`props get mounts2sd.swap.device`]"
					$M2SD_BB echo ""
				;;

				"version") 
					$M2SD_BB echo "$M2SD_VERSION"
				;;

				"fixperm") 
					$M2SD_BB echo "1" > $M2SD_CONFIGS/.fix_permissions
					$M2SD_BB echo "A permissions check will be performed during the next boot!"
				;;

				*)
					CMD_LINE="`$M2SD_BB echo $M2SD_PROPERTIES | $M2SD_BB sed -n "s/.*\($INAME:[a-z0-9]*:[a-z0-9]*\).*/\1/p"`"

					if $M2SD_BB [ ! -z "$CMD_LINE" ]; then
						CMD_VALUE="`$M2SD_BB echo $CMD_LINE | $M2SD_BB cut -d ":" -f 2`"
						CMD_TYPE="`$M2SD_BB echo $CMD_LINE | $M2SD_BB cut -d ":" -f 3`"

						if $M2SD_BB [ ! -z "$IVALUE" ]; then
							case "$CMD_TYPE" in
								"boolean") 
									if $M2SD_BB [ "$IVALUE" = "enable" ] || $M2SD_BB [ "$IVALUE" = "disable" ]; then
										CHK_EXCEPT="true"

									else
										$M2SD_BB echo "Invalid value. The command '$INAME' only excepts the values 'enable' or 'disable'!"
									fi
								;;

								"option") 
									if $M2SD_BB [ "$IVALUE" = "enable" ] || $M2SD_BB [ "$IVALUE" = "disable" ] || $M2SD_BB [ "$IVALUE" = "auto" ]; then
										CHK_EXCEPT="true"

									else
										$M2SD_BB echo "Invalid value. The command '$INAME' only excepts the values 'enable', 'disable' or 'auto'!"
									fi
								;;

								"integer") 
									if $M2SD_BB [ -z "`$M2SD_BB echo $IVALUE | $M2SD_BB sed 's/[0-9]//g'`" ]; then
										CHK_EXCEPT="true"

									else
										$M2SD_BB echo "Invalid value. The command '$INAME' only excepts numeric values!"
									fi
								;;

								"fstype") 
									if $M2SD_BB [ "$IVALUE" = "auto" ] || $M2SD_BB [ ! -z "`$M2SD_BB cat /proc/filesystems | $M2SD_BB grep $IVALUE | $M2SD_BB grep -v 'nodev'`" ]; then
										CHK_EXCEPT="true"

									else
										$M2SD_BB echo "Invalid or unsupported file system type."
										$M2SD_BB echo "Valid/supported types are either 'auto' or one of the fallowing..."
										$M2SD_BB echo "`$M2SD_BB cat /proc/filesystems | $M2SD_BB grep -v 'nodev'`"
									fi
								;;
							esac

							if $M2SD_BB [ "$CHK_EXCEPT" = "true" ]; then
								$M2SD_BB echo "$IVALUE" > $M2SD_CONFIGS/.$INAME
								$M2SD_BB echo " - Changed M2SD $INAME to $IVALUE. Reboot to make changes take affect!"
							fi

						else
							if $M2SD_BB [ -f $M2SD_CONFIGS/.$INAME ]; then
								$M2SD_BB echo "`$M2SD_BB cat $M2SD_CONFIGS/.$INAME`"

							else
								$M2SD_BB echo "$CMD_VALUE" > $M2SD_CONFIGS/.$INAME
								$M2SD_BB echo "$CMD_VALUE"
							fi
						fi

					else
						$M2SD_BB echo "Invalid command. Type 'm2sd help' to see all available options!"
					fi
				;;
			esac
		fi

	# =========================================================================================
	# INITIATION PART
	# =========================================================================================
	else
		if $M2SD_BB [ -e /sys/class/leds/green/brightness ]; then
			$M2SD_BB echo 1 > /sys/class/leds/green/brightness
		fi

		doLog v "Initiating Mounts2SD (v:$M2SD_VERSION) [`$TOOLBOX date`]"
		doLog v "Initiating the props system..."

		if $M2SD_BB [ "`props initiate`" = "false" ]; then
			doLog e "It was not possible to initate the props system!"; break
		fi

		doLog v "Checking configurations..."

		for i in $M2SD_PROPERTIES; do
			I_INDEX="`$M2SD_BB echo $i | $M2SD_BB cut -d ":" -f 1`"

			if $M2SD_BB [ ! -e $M2SD_CONFIGS/.$I_INDEX ] || $M2SD_BB [ -z "`$M2SD_BB cat $M2SD_CONFIGS/.$I_INDEX`" ]; then
				$M2SD_BB echo "`$M2SD_BB echo $i | $M2SD_BB cut -d ":" -f 2`" > $M2SD_CONFIGS/.$I_INDEX
			fi
		done

		if $M2SD_BB [ -z "`$M2SD_BB cat /init.rc | $M2SD_BB grep exec | $M2SD_BB grep sysinit`" ] && $M2SD_BB [ -z "`$M2SD_BB cat /system/etc/init.local.rc | $M2SD_BB grep exec | $M2SD_BB grep sysinit`" ]; then
			doLog w "SYSINIT MISSING: This script works best using sysinit as an executable rather than an service! Switching to safe mode..."

			# Because running sysinit as an service allows the rest of the boot process to run at the same time,
			# moving things like data and dalvik cache will create problems. The system will keep trying to rebuild these as they are being moved.
			# Also CM has added system dex's to be placed in /cache/dalvik-cache rather than /data/dalvik-cache, so moving /cache to /data or /sd-ext
			# will also create dalvik problems. Instead we turn off data, dalvik and only move /cache/download.

			PROP_DLCACHE="enable"
			PROP_DALVIK="disable"
			PROP_CMDALVIK="disable"
			PROP_DATA="disable"
			M2SD_STATUS="safe-mode"
		else
			PROP_DLCACHE="`$M2SD_BB cat $M2SD_CONFIGS/.dlcache`"
			PROP_DALVIK="`$M2SD_BB cat $M2SD_CONFIGS/.dalvik`" 
			PROP_CMDALVIK="`$M2SD_BB cat $M2SD_CONFIGS/.cmdalvik`"
			PROP_DATA="`$M2SD_BB cat $M2SD_CONFIGS/.data`"
			M2SD_STATUS="loaded"
		fi

		PROP_MEMCACHE="`$M2SD_BB cat $M2SD_CONFIGS/.memcache`" 
		PROP_CACHE="`$M2SD_BB cat $M2SD_CONFIGS/.cache`"
		PROP_EXTFS="`$M2SD_BB cat $M2SD_CONFIGS/.extfs`" 
		PROP_APPS="`$M2SD_BB cat $M2SD_CONFIGS/.apps`"
		PROP_SYSAPPS="`$M2SD_BB cat $M2SD_CONFIGS/.sysapps`"
		PROP_SWAP="`$M2SD_BB cat $M2SD_CONFIGS/.swap`" 
		PROP_READAHEAD="`$M2SD_BB cat $M2SD_CONFIGS/.readahead`"
		PROP_JOURNAL="`$M2SD_BB cat $M2SD_CONFIGS/.journal`" 
		PROP_FSCHK="`$M2SD_BB cat $M2SD_CONFIGS/.fschk`"
		PROP_NOATIME="`$M2SD_BB cat $M2SD_CONFIGS/.noatime`"
		PROP_RMOUNT="`$M2SD_BB cat $M2SD_CONFIGS/.rmount`"

		DEV_SYSTEM=`$M2SD_BB cat /proc/mounts | $M2SD_BB grep "/dev/" | $M2SD_BB grep " /system " | $M2SD_BB cut -d " " -f 1`
		DEV_DATA=`$M2SD_BB cat /proc/mounts | $M2SD_BB grep "/dev/" | $M2SD_BB grep " /data " | $M2SD_BB cut -d " " -f 1`

		y=0
		for i in $DEV_SYSTEM $DEV_DATA; do
			if $M2SD_BB [ -e "$i" ]; then
				MTD_MM="`$M2SD_BB ls -l $i | $M2SD_BB tr -s " " | sed -ne "s/^.*[ ]\([0-9]\+\),[ ]\([0-9]\+\)[ ].*$/\1:\2/p"`"

				if $M2SD_BB [ -e /sys/devices/virtual/bdi/$MTD_MM/read_ahead_kb ]; then
					$M2SD_BB [ "$y" = "0" ] && doLog v "Optimizing /system readahead..." || doLog v "Optimizing /data readahead..."
					$M2SD_BB echo 4 > /sys/devices/virtual/bdi/$MTD_MM/read_ahead_kb
				fi
			fi

			if $M2SD_BB [ "$y" = "0" ]; then
				doLog v "Remounting /system with noatime..."
				$M2SD_BB mount -o remount,noatime,nodiratime,barrier=0,nobh /system

			elif $M2SD_BB [ "$PROP_NOATIME" = "enable" ]; then
				doLog v "Remounting /data with noatime..."
				$M2SD_BB mount -o remount,noatime,nodiratime /data
			fi

			y=$(($y + 1))
		done

		doLog v "Waiting for sdcard to initiate..."

		for MMC_TRIES in `seq 1 8`; do
			for MMC_NUM in `seq 0 9`; do
				if $M2SD_BB [ "`$M2SD_BB cat /sys/block/mmcblk$MMC_NUM/device/type`" = "SD" ]; then
					MMC_DEVICE=/dev/block/mmcblk${MMC_NUM}
					MMC_PARTITIONS="`$M2SD_BB fdisk -l $MMC_DEVICE | awk '/^\// {print $1}'`"
					MMC_MM="`$M2SD_BB ls -l $MMC_DEVICE | $M2SD_BB tr -s " " | sed -ne "s/^.*[ ]\([0-9]\+\),[ ]\([0-9]\+\)[ ].*$/\1:\2/p"`"

					if $M2SD_BB [ -e /sys/devices/virtual/bdi/$MMC_MM/read_ahead_kb ]; then
						doLog v "Setting sd-ext readahead to ${PROP_READAHEAD}kb..."
						$M2SD_BB echo $PROP_READAHEAD > /sys/devices/virtual/bdi/$MMC_MM/read_ahead_kb
					fi

					for i in $MMC_PARTITIONS; do
						if $M2SD_BB [ ! -z "`$M2SD_BB blkid | $M2SD_BB grep $i | $M2SD_BB grep " TYPE"`" ]; then
							FS_TYPE=`$M2SD_BB blkid $i | $M2SD_BB sed 's/.*TYPE=\"\([^\"]*\)\".*/\1/g'`

						else
							unset FS_TYPE

							FS_NUMBER="`$M2SD_BB fdisk -l $MMC_DEVICE | $M2SD_BB grep $i | $M2SD_BB tr -s " " | $M2SD_BB rev | $M2SD_BB cut -d " " -f 2 | $M2SD_BB rev`"

							$M2SD_BB [ "$FS_NUMBER" = "5" ] && FS_TYPE="extended"
							$M2SD_BB [ "$FS_NUMBER" = "82" ] && FS_TYPE="swap"
							$M2SD_BB [ "$FS_NUMBER" = "83" ] && FS_TYPE="linux"
							$M2SD_BB [ -z "$FS_TYPE" ] && FS_TYPE="vfat"
						fi

						if $M2SD_BB [ "$FS_TYPE" != "extended" ]; then
							if $M2SD_BB [ "$FS_TYPE" = "swap" ] && $M2SD_BB [ "$BOOL_SWAP" != "true" ]; then
								props set mounts2sd.swap.device "$i"
								BOOL_SWAP="true"

								if $M2SD_BB [ "$PROP_SWAP" = "enable" ]; then
									$M2SD_BB swapon $i

									if $M2SD_BB [ "$?" = "0" ]; then
										doLog v "Activating SWAP partition..."
										props set mounts2sd.swap.status "loaded"

									else
										doLog w "Could not activate SWAP. Not supported by the kernel!"
									fi
								fi

							elif $M2SD_BB [ "$FS_TYPE" != "vfat" ] && $M2SD_BB [ "$BOOL_SDEXT" != "true" ]; then
								props set mounts2sd.sdext.device "$i"
								BOOL_SDEXT="true"
							
								if $M2SD_BB [ "$FS_TYPE" = "linux" ] || $M2SD_BB [ ! -z "`$M2SD_BB cat /proc/filesystems | $M2SD_BB grep $FS_TYPE | $M2SD_BB grep -v 'nodev'`" ]; then

									# This is used as a hack to break out of at any time
									for ihack in true; do
										MMC_SDEXT="`$M2SD_BB ls -l $i | $M2SD_BB tr -s " " | sed -ne "s/^.*[ ]\([0-9]\+\),[ ]\([0-9]\+\)[ ].*$/\1:\2/p"`"

										if $M2SD_BB [ ! -z "`$M2SD_BB cat /proc/mounts | $M2SD_BB grep -w $i`" ] || $M2SD_BB [ ! -z "`$M2SD_BB cat /proc/mounts | $M2SD_BB grep -w /dev/block/vold/$MMC_SDEXT`" ]; then
											doLog w "The sd-ext partition is already mounted. Unmounting it..."
											$M2SD_BB umount $i
										fi

										if $M2SD_BB [ "$PROP_FSCHK" = "enable" ]; then
											$M2SD_BB [ ! -z "`$M2SD_BB which e2fsck`" ] && CMD_FSCK="`$M2SD_BB which e2fsck`" || CMD_FSCK="$M2SD_BB e2fsck"

											doLog v "Running e2fsck on sd-ext..."
											$CMD_FSCK -y -D $i
									
											E2STATUS=$?

											if $M2SD_BB [ $E2STATUS -gt 0 ] && $M2SD_BB [ $E2STATUS -lt 4 ]; then
												doLog e "Error detected while checking sd-ext. Auto correction was performed!"

											elif $M2SD_BB [ $E2STATUS -gt 0 ]; then
												doLog e "Error detected while checking sd-ext. Everything was left uncorrected!"
											fi
										fi

										if $M2SD_BB [ "$FS_TYPE" = "ext4" ] || $M2SD_BB [ "$PROP_EXTFS" = "ext4" ]; then
											$M2SD_BB [ ! -z "`$M2SD_BB which tune2fs`" ] && CMD_TUNE2FS="`$M2SD_BB which tune2fs`" || CMD_TUNE2FS="$M2SD_BB tune2fs"

											if $M2SD_BB [ "$PROP_JOURNAL" = "disable" ]; then
												doLog v "Disabling journal on sd-ext..."
												$CMD_TUNE2FS -O ^has_journal $i

											else 	
												doLog v "Enabling journal on sd-ext..."
												$CMD_TUNE2FS -O has_journal $i
											fi

										elif $M2SD_BB [ "$FS_TYPE" = "ext3" ] || $M2SD_BB [ "$PROP_EXTFS" = "ext3" ]; then
											doLog v "Preparing to mount sd-ext without journal..."
											$M2SD_BB [ -z "$OPTIONS" ] && OPTIONS="noload" || OPTIONS="$OPTIONS,noload"
										fi

										if $M2SD_BB [ "$PROP_NOATIME" = "enable" ]; then
											$M2SD_BB [ -z "$OPTIONS" ] && OPTIONS="noatime,nodiratime" || OPTIONS="$OPTIONS,noatime,nodiratime"
										fi

										if $M2SD_BB [ ! -d /sd-ext ]; then
											$M2SD_BB mount -o remount,rw /
											$M2SD_BB mkdir /sd-ext
											$M2SD_BB mount -o remount,ro /
										fi

										SDEXT_PATH="/sd-ext"

										if [ "$PROP_RMOUNT" = "enable" ]; then
											doLog v "Moving internal nand mount point from /data to /sd-ext..."
											$M2SD_BB mount --move /data /sd-ext

											if $M2SD_BB [ ! -z "`$M2SD_BB cat /proc/mounts | $M2SD_BB grep " /sd-ext "`" ]; then
												SDEXT_PATH="/data"
												M2SD_CONFIGS=/sd-ext/.m2sd
												props set mounts2sd.rmount.status "loaded"

											else
												doLog w "It was not possible to move the internal nand data mount point to /sd-ext!"
											fi
										fi

										if $M2SD_BB [ ! -z "$OPTIONS" ]; then
											$M2SD_BB mount -o $OPTIONS -t $PROP_EXTFS $i $SDEXT_PATH
										else
											$M2SD_BB mount -t $PROP_EXTFS $i $SDEXT_PATH
										fi

										if $M2SD_BB [ ! -z "`$M2SD_BB cat /proc/mounts | $M2SD_BB grep -w $i`" ]; then
											$M2SD_BB [ $PROP_EXTFS = "auto" ] && SDEXT_MOUNT_LOG="The sd-ext partition was mounted successfully at $SDEXT_PATH using auto detection of the file system type!" || SDEXT_MOUNT_LOG="The sd-ext partition was mounted successfully at $SDEXT_PATH forced as $PROP_EXTFS!"

											doLog v "$SDEXT_MOUNT_LOG"

											$M2SD_BB chown 1000.1000 $SDEXT_PATH
											$M2SD_BB chmod 771 $SDEXT_PATH

											DO_REVERT="local misc property system tombstones backup drm user resource-cache"
											DO_MOVE=""

											$M2SD_BB [ "$PROP_DALVIK" = "enable" ] && DO_MOVE="$DO_MOVE dalvik-cache" || DO_REVERT="$DO_REVERT dalvik-cache"
											$M2SD_BB [ "$PROP_DATA" = "enable" ] && DO_MOVE="$DO_MOVE data" || DO_REVERT="$DO_REVERT data"
											$M2SD_BB [ "$PROP_APPS" = "enable" ] && DO_MOVE="$DO_MOVE app app-private" || DO_REVERT="$DO_REVERT app app-private"

											for x in $DO_REVERT; do
												if $M2SD_BB [ -d /sd-ext/$x ] && $M2SD_BB [ ! -L /sd-ext/$x ] && $M2SD_BB [ ! -z "`$M2SD_BB ls -v /sd-ext/$x`" ]; then
													doLog v "Reverting /sd-ext/$x back to /data/$x..."

													if $M2SD_BB [ -L /data/$x ]; then
														$M2SD_BB rm -rf /data/$x
													fi

													if $M2SD_BB [ ! -d /data/$x ]; then
														$M2SD_BB mkdir /data/$x
														$M2SD_BB chown 1000.1000 /data/$x
														$M2SD_BB chmod 771 /data/$x
													fi

													if $M2SD_BB [ "$x" != "dalvik-cache" ]; then
														for tmp in /sd-ext/$x/*; do
															tmpn="`$M2SD_BB basename $tmp`"

															if $M2SD_BB [ -e /data/$x/$tmpn ]; then
																$M2SD_BB rm -rf /data/$x/$tmpn
															fi

															$M2SD_BB mv -f /sd-ext/$x/$tmpn /data/$x/
														done

														if $M2SD_BB [ ! -z "`$M2SD_BB ls -v /sd-ext/$x`" ]; then
															doLog e "Not all from /sd-ext/$x could be moved to /data/$x. Check available disk space!"

														else
															$M2SD_BB rmdir /sd-ext/$x
														fi
													else
														$M2SD_BB rm -rf /sd-ext/$x
													fi

												else
													$M2SD_BB rm -rf /sd-ext/$x
												fi
											done

											for x in $DO_MOVE; do
												if $M2SD_BB [ ! -d /sd-ext/$x ] || $M2SD_BB [ -L /sd-ext/$x ]; then
													if $M2SD_BB [ -L /sd-ext/$x ]; then
														$M2SD_BB rm -rf /sd-ext/$x
													fi 

													$M2SD_BB mkdir /sd-ext/$x
													$M2SD_BB chown 1000.1000 /sd-ext/$x
													$M2SD_BB chmod 771 /sd-ext/$x
												fi

												if $M2SD_BB [ -d /data/$x ] && $M2SD_BB [ ! -L /data/$x ] && $M2SD_BB [ ! -z "`$M2SD_BB ls -v /data/$x`" ]; then
													if $M2SD_BB [ "$x" = "dalvik-cache" ]; then
														doLog v "Clearing dalvik cache to prepare sd-ext linking..."

														$M2SD_BB rm -rf /data/$x/*

													else
														doLog v "Moving content from /data/$x to /sd-ext/$x..."

														for tmp in /data/$x/*; do
															tmpn="`$M2SD_BB basename $tmp`"

															if $M2SD_BB [ -e /sd-ext/$x/$tmpn ]; then
																$M2SD_BB rm -rf /sd-ext/$x/$tmpn
															fi

															$M2SD_BB mv -f /data/$x/$tmpn /sd-ext/$x/
														done

														if $M2SD_BB [ ! -z "`$M2SD_BB ls -v /data/$x`" ]; then
															doLog e "Not all from /data/$x could be moved to /sd-ext/$x. Check available disk space!"
														fi
													fi

												elif $M2SD_BB [ ! -d /data/$i ] || $M2SD_BB [ -L /data/$i ]; then
													$M2SD_BB rm -rf /data/$x

													$M2SD_BB mkdir /data/$x
													$M2SD_BB chown 1000.1000 /data/$x
													$M2SD_BB chmod 771 /data/$x
												fi

												doLog v "Linking /data/$x to /sd-ext/$x..."

												$M2SD_BB mount --bind /sd-ext/$x /data/$x

												if $M2SD_BB [ ! -z "`$M2SD_BB cat /proc/mounts | $M2SD_BB grep " /data/$x "`" ]; then
													$M2SD_BB [ "$x" = "app" ] && props set mounts2sd.sdext.status.apps "loaded"
													$M2SD_BB [ "$x" = "data" ] && props set mounts2sd.sdext.status.data "loaded"
													$M2SD_BB [ "$x" = "dalvik-cache" ] && props set mounts2sd.sdext.status.dalvik "loaded"

												else
													doLog w "Error while linking /data/$x to /sd-ext/$x!"
												fi
											done

											$M2SD_BB [ "$PROP_SYSAPPS" = "enable" ] && props set mounts2sd.sdext.status.sysapps "loaded"
											$M2SD_BB [ "$PROP_SYSAPPS" = "enable" ] && SYSAPPS_TO="/sd-ext/app-system" || SYSAPPS_TO="/data/app-system"
											$M2SD_BB [ "$PROP_SYSAPPS" = "enable" ] && SYSAPPS_FROM="/data/app-system" || SYSAPPS_FROM="/sd-ext/app-system"

											if $M2SD_BB [ -d $SYSAPPS_FROM ] && $M2SD_BB [ ! -z "`$M2SD_BB ls -v $SYSAPPS_FROM`" ]; then
												doLog v "Moving content from $SYSAPPS_FROM to $SYSAPPS_TO..."

												if $M2SD_BB [ ! -d $SYSAPPS_TO ]; then
													$M2SD_BB mkdir $SYSAPPS_TO
													$M2SD_BB chown 1000.1000 $SYSAPPS_TO
													$M2SD_BB chmod 771 $SYSAPPS_TO
												fi

												for tmp in $SYSAPPS_FROM/*; do
													tmpn="`$M2SD_BB basename $tmp`"

													if $M2SD_BB [ -e $SYSAPPS_TO/$tmpn ]; then
														$M2SD_BB rm -rf $SYSAPPS_TO/$tmpn
													fi

													$M2SD_BB mv -f $SYSAPPS_FROM/$tmpn $SYSAPPS_TO/
												done

												if $M2SD_BB [ ! -z "`$M2SD_BB ls -v $SYSAPPS_FROM`" ]; then
													doLog e "Not all from $SYSAPPS_FROM could be moved to $SYSAPPS_TO. Check available disk space!"

												else
													$M2SD_BB rm -rf $SYSAPPS_FROM
												fi
											fi

											$M2SD_BB mount -o remount,rw /system

											for tmp in /system/app/*; do
												if $M2SD_BB [ -L $tmp ] && $M2SD_BB [ ! -e "`$M2SD_BB readlink $tmp`" ]; then
													$M2SD_BB rm -rf $tmp
												fi
											done

											if $M2SD_BB [ -d $SYSAPPS_TO ]; then
												doLog v "Linking content from $SYSAPPS_TO to /system/app..."

												for tmp in $SYSAPPS_TO/*; do
													tmpn="`$M2SD_BB basename $tmp`"

													if $M2SD_BB [ ! -e /system/app/$tmpn ] || $M2SD_BB [ ! -L /system/app/$tmpn ]; then
														$M2SD_BB [ -e /system/app/$tmpn ] && $M2SD_BB rm -rf /system/app/$tmpn
														$M2SD_BB ln -s $tmp /system/app/
													fi
												done
											fi

											$M2SD_BB mount -o remount,ro /system

											if $M2SD_BB [ ! -f $M2SD_CONFIGS/.fix_permissions ] || $M2SD_BB [ "`$M2SD_BB cat $M2SD_CONFIGS/.fix_permissions`" = "1" ]; then
												doLog v "Performing a one time permissions check..."
												$M2SD_BB echo "0" > $M2SD_CONFIGS/.fix_permissions
												fix_permissions -l -r
											fi

										else
											doLog e "Error while mounting the sd-ext partition!"
											props remove mounts2sd.rmount.status
											M2SD_CONFIGS=/data/.m2sd
										fi
									done

									# Make sure we have all needed folders, even in R-Mount mode.
									# This will reduce the risc of heap errors during boot.
									for x in misc misc/bluetoothd misc/bluetooth misc/keystore misc/keychain misc/vpn misc/systemkeys misc/wifi local local/tmp app app-private app-system data dalvik-cache property; do
										if $M2SD_BB [ ! -d /data/$x ]; then
											$M2SD_BB mkdir /data/$x
											$M2SD_BB chmod 771 /data/$x
											$M2SD_BB chown 1000.1000 /data/$x

											$M2SD_BB [ ! -z "`echo $x | grep bluetoothd`" ] && $M2SD_BB chown 1002.1002 /data/$x
											$M2SD_BB [ ! -z "`echo $x | grep keystore`" ] && $M2SD_BB chown 1017.1017 /data/$x
											$M2SD_BB [ ! -z "`echo $x | grep vpn`" ] && $M2SD_BB chown 1000.1016 /data/$x
											$M2SD_BB [ ! -z "`echo $x | grep wifi`" ] && $M2SD_BB chown 1010.1010 /data/$x
											$M2SD_BB [ ! -z "`echo $x | grep local`" ] && $M2SD_BB chown 2000.2000 /data/$x
											$M2SD_BB [ ! -z "`echo $x | grep property`" ] && $M2SD_BB chown 0.0 /data/$x
										fi
									done

								else
									doLog e "The sd-ext partition contains a file system not supported by the kernel!"
								fi
							fi
						fi
					done

					break 2
				fi
			done

			if $M2SD_BB [ $MMC_TRIES -eq 8 ]; then
				doLog e "Timedout waiting for SDCard to initiate!"; break

			else
				sleep 1
			fi
		done

		if $M2SD_BB [ "$PROP_CACHE" = "enable" ] || ( $M2SD_BB [ "$PROP_CACHE" = "auto" ] && $M2SD_BB [ "`$M2SD_BB df -m /cache | $M2SD_BB tail -n1 | $M2SD_BB tr -s ' ' | $M2SD_BB cut -d ' ' -f2`" -lt 40 ] ); then
			if $M2SD_BB [ "$PROP_DLCACHE" = "enable" ]; then
				CACHE_LOCATION="/cache/download"

			else
				CACHE_LOCATION="/cache"
			fi

			[ "`props get mounts2sd.rmount.status`" = "enable" ] && SDEXT_LOC="/data" || SDEXT_LOC="/sd-ext"

			if $M2SD_BB [ "$PROP_MEMCACHE" != "enable" ] && $M2SD_BB [ ! -z "`$M2SD_BB cat /proc/mounts | $M2SD_BB grep " $SDEXT_LOC "`" ] && ( $M2SD_BB [ "$PROP_CACHE" != "auto" ] || $M2SD_BB [ "`$M2SD_BB df -m $SDEXT_LOC | $M2SD_BB tail -n1 | $M2SD_BB tr -s ' ' | $M2SD_BB cut -d ' ' -f4`" -gt 39 ] ); then 
				props set mounts2sd.cache.device "`props get mounts2sd.sdext.device`"

				CACHE_PATH="${SDEXT_LOC}${CACHE_LOCATION}"

			elif $M2SD_BB [ "$PROP_MEMCACHE" != "enable" ] && ( $M2SD_BB [ "$PROP_CACHE" != "auto" ] || $M2SD_BB [ "`$M2SD_BB df -m /data | $M2SD_BB tail -n1 | $M2SD_BB tr -s ' ' | $M2SD_BB cut -d ' ' -f4`" -gt 39 ] ); then
				props set mounts2sd.cache.device "$DEV_DATA"

				CACHE_PATH="/data$CACHE_LOCATION"

			else
				props set mounts2sd.cache.device "tmpfs"

				CACHE_PATH="/tmp$CACHE_LOCATION"
			fi

			CACHE_DIRS="$CACHE_LOCATION $CACHE_PATH"

			if $M2SD_BB [ ! -z "`$M2SD_BB cat /proc/mounts | $M2SD_BB grep " $CACHE_LOCATION "`" ]; then
				doLog v "Umounting $CACHE_LOCATION to make the directory ready for linking..."
				$M2SD_BB umount /cache
			fi

			$M2SD_BB mount -o remount,rw /
			for i in $CACHE_DIRS; do
				if $M2SD_BB [ ! -d $i ] || $M2SD_BB [ -L $i ]; then
					if $M2SD_BB [ -L $i ]; then
						$M2SD_BB rm -rf $i
					fi

					$M2SD_BB mkdir -p $i
					$M2SD_BB chown -R 1000.2001 $i
					$M2SD_BB chmod -R 771 $i
				fi
			done
			$M2SD_BB mount -o remount,ro /

			doLog v "Linking $CACHE_LOCATION to $CACHE_PATH..."
			$M2SD_BB mount --bind $CACHE_PATH $CACHE_LOCATION

			if $M2SD_BB [ ! -z "`$M2SD_BB cat /proc/mounts | $M2SD_BB grep " $CACHE_LOCATION "`" ]; then
				if $M2SD_BB [ ! -d /cache/download ]; then
					$M2SD_BB mkdir /cache/download
					$M2SD_BB chown 1000.2001 /cache/download
					$M2SD_BB chmod 771 /cache/download

				else
					$M2SD_BB rm -rf /cache/download/*
				fi

				props set mounts2sd.cache.status "loaded"
				props set mounts2sd.cache.location "$CACHE_LOCATION"

			else
				doLog w "Error while linking $CACHE_LOCATION to $CACHE_PATH!"
			fi
		fi

		if $M2SD_BB [ "$PROP_CACHE" = "enable" ] || ( $M2SD_BB [ "$PROP_CACHE" = "auto" ] && $M2SD_BB [ "`$M2SD_BB df -m /data | $M2SD_BB tail -n1 | $M2SD_BB tr -s ' ' | $M2SD_BB cut -d ' ' -f4`" -lt 55 ] ); then 
			for i in /tmp/data-tmp /data/local/tmp; do
				if $M2SD_BB [ ! -d $i ]; then
					$M2SD_BB mkdir $i
					$M2SD_BB chown 2000.2000 $i
					$M2SD_BB chmod 771 $i
				fi
			done

			doLog v "Linking /tmp/data-tmp to /data/local/tmp..."
			$M2SD_BB mount --bind /tmp/data-tmp /data/local/tmp
		fi

		if $M2SD_BB [ "$PROP_CMDALVIK" = "enable" ]; then
			if $M2SD_BB [ ! -d /cache/dalvik-cache ]; then
				$M2SD_BB mkdir /cache/dalvik-cache

			else
				if $M2SD_BB [ ! -z "`$M2SD_BB ls -v /cache/dalvik-cache`" ]; then
					# If /cache/dalvik-cache has been used, /data/dalvik-cache is outdated.
					# We remove any old files from /data/dalvik-cache to avoid problems.
					for i in /cache/dalvik-cache/*; do
						dexname="`$M2SD_BB basename $i`"

						if $M2SD_BB [ -e /data/dalvik-cache/$dexname ]; then
							$M2SD_BB rm -rf /data/dalvik-cache/$dexname
						fi
					done

					$M2SD_BB rm -rf /cache/dalvik-cache/*
				fi
			fi

			if $M2SD_BB [ ! -d /data/dalvik-cache ]; then
				$M2SD_BB mkdir /data/dalvik-cache
				$M2SD_BB chown 1000.1000 /data/dalvik-cache
				$M2SD_BB chmod 771 /data/dalvik-cache
			fi

			doLog v "Linking /cache/dalvik-cache to /data/dalvik-cache..."
			$M2SD_BB mount --bind /data/dalvik-cache /cache/dalvik-cache

			if $M2SD_BB [ ! -z "`$M2SD_BB cat /proc/mounts | $M2SD_BB grep " /cache/dalvik-cache "`" ]; then
				props set mounts2sd.cmdalvik.status "loaded"

			else
				doLog w "Error while linking /cache/dalvik-cache to /data/dalvik-cache!"
			fi
		fi

		doLog v "Mounts2SD has been loaded!"

		$M2SD_BB echo "" >> $M2SD_CONFIGS/m2sd.log
		$M2SD_BB echo "Registered properties:" >> $M2SD_CONFIGS/m2sd.log
		$M2SD_BB echo "----------------------" >> $M2SD_CONFIGS/m2sd.log
		props get | grep mounts2sd >> $M2SD_CONFIGS/m2sd.log
		$M2SD_BB echo "" >> $M2SD_CONFIGS/m2sd.log
		$M2SD_BB echo "Mount Points:" >> $M2SD_CONFIGS/m2sd.log
		$M2SD_BB echo "-------------" >> $M2SD_CONFIGS/m2sd.log
		if $M2SD_BB [ ! -z "$MMC_DEVICE" ]; then
			$M2SD_BB df -h | $M2SD_BB grep $MMC_DEVICE >> $M2SD_CONFIGS/m2sd.log
		fi
		$M2SD_BB echo "" >> $M2SD_CONFIGS/m2sd.log

		props set mounts2sd.status "$M2SD_STATUS"

		if $M2SD_BB [ -e /sys/class/leds/green/brightness ]; then
			$M2SD_BB echo 0 > /sys/class/leds/green/brightness
		fi
	fi
done
